#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-resolvelib
Version  : 0.8.1
Release  : 9
URL      : https://files.pythonhosted.org/packages/ac/20/9541749d77aebf66dd92e2b803f38a50e3a5c76e7876f45eb2b37e758d82/resolvelib-0.8.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ac/20/9541749d77aebf66dd92e2b803f38a50e3a5c76e7876f45eb2b37e758d82/resolvelib-0.8.1.tar.gz
Summary  : Resolve abstract dependencies into concrete ones
Group    : Development/Tools
License  : ISC
Requires: pypi-resolvelib-license = %{version}-%{release}
Requires: pypi-resolvelib-python = %{version}-%{release}
Requires: pypi-resolvelib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: resolvelib
Provides: resolvelib-python
Provides: resolvelib-python3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
==========
ResolveLib
==========
ResolveLib at the highest level provides a ``Resolver`` class that includes
dependency resolution logic. You give it some things, and a little information
on how it should interact with them, and it will spit out a resolution result.

%package license
Summary: license components for the pypi-resolvelib package.
Group: Default

%description license
license components for the pypi-resolvelib package.


%package python
Summary: python components for the pypi-resolvelib package.
Group: Default
Requires: pypi-resolvelib-python3 = %{version}-%{release}

%description python
python components for the pypi-resolvelib package.


%package python3
Summary: python3 components for the pypi-resolvelib package.
Group: Default
Requires: python3-core
Provides: pypi(resolvelib)

%description python3
python3 components for the pypi-resolvelib package.


%prep
%setup -q -n resolvelib-0.8.1
cd %{_builddir}/resolvelib-0.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641489731
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-resolvelib
cp %{_builddir}/resolvelib-0.8.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-resolvelib/e8f006df7200afbbdd3a2e7a85e487338dc75073
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-resolvelib/e8f006df7200afbbdd3a2e7a85e487338dc75073

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
